version: 0.0
os: linux
files:
 - source: /
   destination: /root/django
permissions:
  - object: scripts
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - file
  - object: /root/django/scripts
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - file

hooks:
  BeforeInstall:
   - location: /scripts/before_update.sh
     timeout: 300
     runas: root
  Install:
   - location: /scripts/update_project.sh
     timeout: 300
     runas: root