# Generated by Django 3.1 on 2022-08-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=500)),
                ('model', models.CharField(default='', max_length=80)),
                ('kilo', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.CharField(max_length=30)),
                ('quality_score', models.IntegerField(default=100)),
                ('price_score', models.IntegerField(default=100)),
                ('img', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
