# Generated by Django 3.1 on 2022-08-17 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=500)),
                ('model', models.CharField(default='', max_length=80)),
                ('kilo', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('owner', models.CharField(max_length=30)),
                ('quality_score', models.IntegerField(default=100)),
                ('price_score', models.IntegerField(default=100)),
                ('img', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='OptionD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt1', models.BooleanField(default=False)),
                ('opt2', models.BooleanField(default=False)),
                ('opt3', models.BooleanField(default=False)),
                ('opt4', models.BooleanField(default=False)),
                ('opt5', models.BooleanField(default=False)),
                ('opt6', models.BooleanField(default=False)),
                ('opt7', models.BooleanField(default=False)),
                ('opt8', models.BooleanField(default=False)),
                ('opt9', models.BooleanField(default=False)),
                ('opt10', models.BooleanField(default=False)),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MTV.car')),
            ],
        ),
        migrations.CreateModel(
            name='OptionC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt1', models.BooleanField(default=False)),
                ('opt2', models.BooleanField(default=False)),
                ('opt3', models.BooleanField(default=False)),
                ('opt4', models.BooleanField(default=False)),
                ('opt5', models.BooleanField(default=False)),
                ('opt6', models.BooleanField(default=False)),
                ('opt7', models.BooleanField(default=False)),
                ('opt8', models.BooleanField(default=False)),
                ('opt9', models.BooleanField(default=False)),
                ('opt10', models.BooleanField(default=False)),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MTV.car')),
            ],
        ),
        migrations.CreateModel(
            name='OptionB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt1', models.BooleanField(default=False)),
                ('opt2', models.BooleanField(default=False)),
                ('opt3', models.BooleanField(default=False)),
                ('opt4', models.BooleanField(default=False)),
                ('opt5', models.BooleanField(default=False)),
                ('opt6', models.BooleanField(default=False)),
                ('opt7', models.BooleanField(default=False)),
                ('opt8', models.BooleanField(default=False)),
                ('opt9', models.BooleanField(default=False)),
                ('opt10', models.BooleanField(default=False)),
                ('opt11', models.BooleanField(default=False)),
                ('opt12', models.BooleanField(default=False)),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MTV.car')),
            ],
        ),
        migrations.CreateModel(
            name='OptionA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt1', models.BooleanField(default=False)),
                ('opt2', models.BooleanField(default=False)),
                ('opt3', models.BooleanField(default=False)),
                ('opt4', models.BooleanField(default=False)),
                ('opt5', models.BooleanField(default=False)),
                ('opt6', models.BooleanField(default=False)),
                ('opt7', models.BooleanField(default=False)),
                ('opt8', models.BooleanField(default=False)),
                ('opt9', models.BooleanField(default=False)),
                ('opt10', models.BooleanField(default=False)),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MTV.car')),
            ],
        ),
        migrations.CreateModel(
            name='MyCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mycar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MTV.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='manager',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='MTV.manager'),
        ),
    ]
