# Generated by Django 3.1 on 2022-08-10 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MTV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='manager',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='MTV.manager'),
        ),
    ]
