# Generated by Django 3.1 on 2022-08-12 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MTV', '0003_optiona_optionb_optionc_optiond'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optiona',
            old_name='car',
            new_name='Car',
        ),
        migrations.RenameField(
            model_name='optionb',
            old_name='car',
            new_name='Car',
        ),
        migrations.RenameField(
            model_name='optionc',
            old_name='car',
            new_name='Car',
        ),
        migrations.RenameField(
            model_name='optiond',
            old_name='car',
            new_name='Car',
        ),
    ]
